# Worker 项目的名称
name = "ai-image-generator"

# 你的 Cloudflare 账户 ID，需要替换为实际的 ID
account_id = "364cb1e8c4f4681bfa4a0815184297ab"

# 指定主文件
main = "index.js"

[env.production]
workers_dev = true
